### GET - All owners

GET http://localhost:8000/api/owner

### GET - Single Owner

GET http://localhost:8000/api/owner/3


### POST - create new photo resource
POST http://localhost:8000/api/owner/
Content-Type: application/json

{
   "name": "Jonnie Grieve",
   "copyright": "@copyright 2020 Jonathan"
}

### PUT - request change to first author with post
POST http://localhost:8000/api/owner/1?_method=PUT
Content-Type: application/json

{
    "name": "Guil Hernandez",
    "copyright": "@copyright Software Development Teacher 2020"
}


### DELETE - a specific resource

### DELETE http://localhost:8000/api/owner/1
DELETE http://127.0.0.1:8000/api/owner/6


### PHOTOS REQUESTS

# GET - all photos
GET http://localhost:8000/api/photos

### GET - specific photo
GET http://localhost:8000/api/photos/1