
### ALL PHOTOS

GET http://localhost:8000/api/photos

### SINGLE PHOTOS

GET http://localhost:8000/api/photos/1

### ALL OWNERS

GET http://localhost:8000/api/owner

### SINGLE OWNER

GET http://localhost:8000/api/owner/3


### CREATE/POST create new photo resource
POST http://localhost:8000/api/owner/
Content-Type: application/json

{
   "name": "Jonathan Grieve",
   "copyright": "@copyright 2020 Jonathan"
}

### PUT request change to first author
POST http://localhost:8000/api/owner/1?_method=PUT
Content-Type: application/json

{
    "name": "Guil Hernandez",
    "copyright": "@copyright Software Development Teacher 2020"
}
