<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="../icon.png" type="image/png">
    <title>Developing Projects with Cursor AI | JGDM</title>
    <link rel="stylesheet" href="style.css"> <!-- Link to your CSS file -->
</head>
<body>
    <header>

        <h1>Development with Cursor AI</h1>
       
    </header>

    <main>
        <section id="section---about--cursor">

            <h2>About Cursor AI</h2>

            <p>Cursor AI is the leading Text Editor that bundles with AI enhances your browsing experience by providing intelligent suggestions and actions based on your codebase..</p>

        </section>
        <section>

            <h2>Features</h2>

            <ul>
                <li class="cursor---featues">Smart suggestions</li>
                <li class="cursor---featues">Context-aware actions</li>
                <li class="cursor---featues">Customizable settings</li>
            </ul>

        </section>

        <section id="section---howit--works">

            <h2>How it works</h2>

            <ul>

                <li>Cursor AI analyzes your codebase and identifies the most relevant code snippets.</li>

                <li><strong class="item---howit--works">Chat</strong> - Develop as you go with an AI Chatbox that knows your codebase. You can add particular blocks of code to the context with Ctrl+Shift+L or "@." You can chat with your entire codebase with Ctrl+Enter.   Use @Codebase or Ctrl Enter to... </li>

                <li><strong class="item---howit--works">Terminal Ctrl K</strong> - Use Ctrl K in the terminal to write terminal commands in plain english. Cursor will convert them into the terminal command you need.</li>
                
                <li><strong class="item---howit--works">Quick Questions:</strong> highlight code, select and click on "quick question" to ask a question and get an answer.</li>
            </ul>
            
        </section>

        <section id="section---projects--in--cursor">

            <h2>Projects I've developed with Cursor</h2>

            <p><a href="https://projects.jonniegrieve.co.uk/darts_scorer_app" target="_blank" class="projects---in--cursor">Darts Scorer App</a> - This is a simple web application that you can use to score your Darts matches. </p>
            <p><a href="https://projects.jonniegrieve.co.uk/score_comparator" target="_blank" class="projects---in--cursor">Score Comparator - Football</a> - Match up your teams and see how their results compare over a season.</p>
            <p><a href="https://projects.jonniegrieve.co.uk/work_counter" target="_blank" class="projects---in--cursor">Work Counter</a> - Apply your hourly rate and watch the pennies count up until your job is done. (This could make a great standalome app or PWA).</p>    
            <p><a href="https://projects.jonniegrieve.co.uk/ai/dynamic_list" target="_blank" class="projects---in--cursor">Dynamic List - Sqlite and PHP</a> - A list that persists - going beyond use of localstorage </p>  
            <p><a href="https://projects.jonniegrieve.co.uk/bird_identifier" target="_blank" class="projects---in--cursor">Bird Identifier</a> - Use this space to search identify the bird species that you see when you're out and about </p>
            <!--<p><a href="https://projects.jonniegrieve.co.uk/todo_list" target="_blank" class="projects---in--cursor">Interactive Todo List with Javascript and PHP</a> - A list that persists - going beyond use of localstorage</p>-->
            <!--<p><a href="https://projects.jonniegrieve.co.uk/snooker_scorer" target="_blank" class="projects---in--cursor">Snooker Scorer</a></p>-->
        </section>
    </main>
    <footer>
        <p>Page design generated by Cursor AI &copy; (2025) Cursor AI.</p>
    </footer>
</body>
</html>
